(()=>{'use strict';
const A=document.getElementById('app'),K='oc-ready-progress-v1',L='ABCD',SUB=['English','Mathematics','Science'],FULL={English:35,Mathematics:30,Science:30},RELEASE='6.9.0';
const BANK=Array.isArray(window.AW_BANK)?window.AW_BANK:[],BYID=new Map(BANK.map(q=>[q.id,q]));
let S='home',sess=null,P=load(),speaking=false,busy=false;
function def(){return{attempts:[],seenIds:[],reviewQueue:[],recentFamilies:[],xp:0,streak:0,skillStats:{},lastActiveDate:null};}
function load(){try{const x=JSON.parse(localStorage.getItem(K)||'{}');return Object.assign(def(),x,{attempts:Array.isArray(x.attempts)?x.attempts:[],seenIds:Array.isArray(x.seenIds)?x.seenIds:[],reviewQueue:Array.isArray(x.reviewQueue)?x.reviewQueue:[],recentFamilies:Array.isArray(x.recentFamilies)?x.recentFamilies:[],skillStats:x.skillStats&&typeof x.skillStats==='object'?x.skillStats:{}})}catch(_){return def();}}
function save(){try{localStorage.setItem(K,JSON.stringify(P))}catch(_){}}
function esc(x){return String(x??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));}
function seed(){const d=new Date();return +(String(d.getFullYear())+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0'));}
function shuffle(a,s){let x=s|0,b=[...a];for(let i=b.length-1;i>0;i--){x^=x<<13;x^=x>>>17;x^=x<<5;const j=Math.floor(((x>>>0)/4294967296)*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b;}
function skillStat(q){return P.skillStats[q.subject+'|'+(q.subskill||q.skill)]||{a:0,c:0,guess:0,certainWrong:0};}
function prio(q){const x=skillStat(q);if(!x.a)return 0;return(x.certainWrong||0)*4+(1-x.c/x.a)*3+(x.guess||0)/x.a*2;}
function familyKey(q){return q.subject+'|'+q.family;}
function dailyFast(){const t0=performance.now(),sd=seed(),seen=new Set(P.seenIds),recent=new Set((P.recentFamilies||[]).slice(-84)),used=new Set(),out=[];
  for(const s of SUB){const base=BANK.filter(q=>q.subject===s&&!seen.has(q.id)),preferred=base.filter(q=>!recent.has(familyKey(q))),weak=preferred.filter(q=>prio(q)>1).sort((a,b)=>prio(b)-prio(a)),fresh=shuffle(preferred,sd+s.length*19),cooldown=shuffle(base.filter(q=>recent.has(familyKey(q))),sd+s.length*29),cand=[...weak,...fresh,...cooldown];
    for(const q of cand){const f=familyKey(q);if(used.has(f))continue;used.add(f);out.push(q);if(out.filter(x=>x.subject===s).length===4)break;}
    if(out.filter(x=>x.subject===s).length<4){for(const q of cand){if(out.some(x=>x.id===q.id))continue;out.push(q);if(out.filter(x=>x.subject===s).length===4)break;}}
  }
  if(out.length<12){const rest=shuffle(BANK.filter(q=>!seen.has(q.id)&&!out.some(x=>x.id===q.id)),sd+97);for(const q of rest){if(out.length===12)break;out.push(q)}}
  if(out.length<12){window.__AW_BANK_EXHAUSTED=true;}
  const vis=out.map((q,i)=>q.kind==='visual'?i:-1).filter(i=>i>=0);if(vis.length>2){for(const i of vis.slice(2)){const rep=shuffle(BANK.filter(q=>q.subject===out[i].subject&&q.kind!=='visual'&&!seen.has(q.id)&&!out.some((x,j)=>j!==i&&x.id===q.id)&&!used.has(familyKey(q))),sd+i*41)[0];if(rep){used.delete(familyKey(out[i]));out[i]=rep;used.add(familyKey(rep))}}}
  window.__AW_LAST_PICK_MS=Math.round((performance.now()-t0)*100)/100;return shuffle(out.slice(0,12),sd+173);
}
function subjectTest(subject){const n=FULL[subject],sd=seed()+subject.length*101,seen=new Set(P.seenIds),pool=BANK.filter(q=>q.subject===subject),fresh=shuffle(pool.filter(q=>!seen.has(q.id)),sd),rest=shuffle(pool.filter(q=>seen.has(q.id)),sd+9),all=[...fresh,...rest],out=[],lastFam=[];for(const q of all){if(lastFam.slice(-2).includes(q.family))continue;out.push(q);lastFam.push(q.family);if(out.length===n)break}if(out.length<n)for(const q of all){if(!out.includes(q)){out.push(q);if(out.length===n)break}}return out.sort((a,b)=>(a.difficulty||2)-(b.difficulty||2));}
function updateStreak(){const t=new Date().toISOString().slice(0,10);if(P.lastActiveDate===t)return;const d=new Date();d.setDate(d.getDate()-1);P.streak=P.lastActiveDate===d.toISOString().slice(0,10)?(P.streak||0)+1:1;P.lastActiveDate=t;}
function stopRead(){if('speechSynthesis'in window)speechSynthesis.cancel();speaking=false;}
function read(){if(!('speechSynthesis'in window)||!sess)return;if(speaking){stopRead();return render()}const q=sess.items[sess.i],u=new SpeechSynthesisUtterance([q.stimulus,q.question,...q.options.map((o,i)=>L[i]+'. '+o)].filter(Boolean).join('. ')),vs=speechSynthesis.getVoices(),v=vs.find(v=>/Karen|Matilda|Samantha/.test(v.name))||vs.find(v=>/^en-AU/.test(v.lang))||vs.find(v=>/^en-/.test(v.lang))||vs[0];if(v)u.voice=v;u.rate=.92;u.pitch=1.04;u.onend=()=>{speaking=false;render()};u.onerror=()=>{speaking=false};speaking=true;speechSynthesis.cancel();speechSynthesis.speak(u);render();}
function shell(x){return`<main class="app"><div class="top"><button class="brand" data-a="home">AWenture</button><button class="link" data-a="parent">Parent</button></div>${x}<div class="footer">AWenture · v${RELEASE} · ICAS Grade 2</div></main>`;}
function home(){const a=P.attempts,last=a.length?a[a.length-1]:null;return shell(`<section class="card"><div class="ey">ICAS Grade 2 · stable calibrated core</div><h1>Hello Alistair 👋</h1><p>ICAS-style adaptive practice with rich stimuli, construction-level novelty and confidence-informed review.</p><button class="primary wide" data-a="daily" ${busy?'disabled':''}>${busy?'Preparing practice…':"Start today's practice"}</button><div class="stats"><div class="stat"><b>${P.streak||0} 🔥</b><small>streak</small></div><div class="stat"><b>${P.xp||0}</b><small>XP</small></div><div class="stat"><b>${last?Math.round(last.score)+'%':'—'}</b><small>latest</small></div></div></section><div class="grid"><button class="tile" data-a="tests"><b>🏁 ICAS Grade 2 tests</b><span>Full-length subject papers</span></button><button class="tile" data-a="progress"><b>📈 Progress</b><span>Skills and confidence</span></button><button class="tile" data-a="collection"><b>🏆 My Collection</b><span>10 achievements · Grey → Bronze → Silver → Gold</span></button></div><section class="card"><div class="ey">Learning path</div><div class="path">✅ ICAS Grade 2</div><div class="path">🔒 ICAS Grade 3</div><div class="path">🔒 NAPLAN Grade 3</div><div class="path">🔒 Opportunity Class</div></section><div class="love">Made with love by Arthur Wang (daddy), 2026</div>`);}
function start(items,type='practice',subject=null){busy=false;sess={items,i:0,ans:{},checked:{},confidence:{},ask:{},flagged:{},type,subject};S='practice';render();}
function stimulus(q){const text=q.stimulus?`<div class="stimulus-text">${esc(q.stimulus).replace(/\n/g,'<br>')}</div>`:'';const visual=q.visual?`<div class="stimulus-visual">${q.visual}</div>`:'';return visual+text||`<div class="stimulus-empty"><span>Read the question carefully.</span></div>`;}
function practice(){const q=sess.items[sess.i],sel=sess.ans[sess.i],ck=sess.checked[sess.i],ask=sess.ask[sess.i],conf=sess.confidence[sess.i],ok=ck&&sel===q.answer,flag=!!sess.flagged[sess.i];return `<main class="test-player"><header class="testbar"><div class="testbrand"><button class="test-home" data-a="home">AWenture</button><span>ICAS-style ${esc(sess.subject||'Grade 2 Practice')}</span></div><div class="teststatus"><b>Question ${sess.i+1} of ${sess.items.length}</b><button class="iconbtn ${flag?'active':''}" data-a="flag" aria-label="Flag question">${flag?'⚑ Flagged':'⚐ Flag'}</button><button class="iconbtn" data-a="read">${speaking?'■ Stop':'🔊 Read'}</button><button class="exitbtn" data-a="home">Exit</button></div></header><div class="progressrail">${sess.items.map((_,i)=>`<button class="progressdot ${i===sess.i?'cur':sess.flagged[i]?'flagged':sess.checked[i]?'answered':''}" data-q="${i}" aria-label="Question ${i+1}">${i+1}</button>`).join('')}</div><section class="testworkspace ${q.kind==='visual'?'visual-question':''}"><div class="stimulus-pane"><div class="pane-label">STIMULUS</div>${stimulus(q)}</div><div class="question-pane"><div class="question-meta">${esc(q.skill)} · ${esc(q.subskill||'')}</div><div class="question-number">Question ${sess.i+1}</div><div class="q">${esc(q.question)}</div><div class="opts test-options">${q.options.map((o,i)=>{const l=L[i];let cl=sel===l?'sel':'';if(ck&&l===q.answer)cl+=' ok';if(ck&&sel===l&&l!==q.answer)cl+=' bad';return`<button class="opt ${cl}" data-o="${l}" ${ck||ask?'disabled':''}><span class="choice">${l}</span><span>${esc(o)}</span></button>`}).join('')}</div>${ask&&!ck?`<div class="confidence"><b>How sure are you?</b><div class="convgrid"><button class="conv" data-c="3">🎯 Certain</button><button class="conv" data-c="2">🙂 Pretty sure</button><button class="conv" data-c="1">🤔 Guessing</button></div></div>`:''}${ck?`<div class="feedback"><b>${ok?'✓ Correct':'Review this one'}</b><p>${esc(q.explanation)}</p>${conf?`<small>${conf===3?'🎯 Certain':conf===2?'🙂 Pretty sure':'🤔 Guessing'}</small>`:''}</div>`:''}</div></section><footer class="testnav"><button class="navbtn" data-a="back" ${sess.i?'':'disabled'}>← Back</button><div class="navhint">${sess.ans[sess.i]?'Answer selected':'Choose one answer'}</div>${ask&&!ck?'<span></span>':`<button class="navbtn primarynav" data-a="${ck?'next':'check'}" ${!ck&&!sel?'disabled':''}>${ck?(sess.i===sess.items.length-1?'Finish':'Next →'):'Check answer'}</button>`}</footer><div class="testfooter">AWenture · v${RELEASE} · ICAS visual-fidelity practice</div></main>`;}
function finish(){let c=0;const seen=new Set(P.seenIds),rq=new Set(P.reviewQueue);sess.items.forEach((q,i)=>{const ok=sess.ans[i]===q.answer,cf=+sess.confidence[i]||1,key=q.subject+'|'+(q.subskill||q.skill);if(ok)c++;seen.add(q.id);ok&&cf>=2?rq.delete(q.id):rq.add(q.id);let z=P.skillStats[key]||{a:0,c:0,guess:0,certainWrong:0};z.a++;if(ok)z.c++;if(cf===1)z.guess++;if(!ok&&cf===3)z.certainWrong++;P.skillStats[key]=z;});updateStreak();const score=100*c/sess.items.length;P.seenIds=[...seen].slice(-900);P.reviewQueue=[...rq].slice(-80);P.recentFamilies=[...(P.recentFamilies||[]),...sess.items.map(familyKey)].slice(-84);P.xp=(P.xp||0)+c*5;P.attempts.push({date:new Date().toISOString(),score,subject:sess.subject||'Daily',type:sess.type,perfect:c===sess.items.length});save();sess.result={c,score};S='results';render();}
function achievements(){const a=P.attempts||[],full=s=>a.filter(x=>x.type==='icas-test'&&x.subject===s).length,perfect=a.filter(x=>x.perfect).length,stats=Object.values(P.skillStats||{}),comeback=stats.filter(x=>x.a>1&&x.c>0).length,conf=stats.filter(x=>x.a>=2&&x.c/x.a>=.8&&(x.guess||0)/x.a<.2).length;return[['🧭','Adventure Streak',P.streak||0,[3,7,14],'days'],['🌱','Practice Explorer',a.length,[3,10,25],'sessions'],['🎯','Perfect Practice',perfect,[1,3,8],'perfects'],['🧠','Confidence Champion',conf,[1,3,6],'skills'],['🔄','Comeback Kid',comeback,[1,3,6],'skills'],['📘','English Explorer',full('English'),[1,3,6],'papers'],['➗','Maths Master',full('Mathematics'),[1,3,6],'papers'],['🔬','Science Star',full('Science'),[1,3,6],'papers'],['👀','Visual Detective',(P.seenIds||[]).filter(id=>BYID.get(id)?.kind==='visual').length,[2,5,10],'visuals'],['🏆','ICAS Challenger',full('English')+full('Mathematics')+full('Science'),[1,3,9],'papers']];}
function collection(){return shell(`<section class="card"><div class="ey">My Collection</div><h1>10 achievements</h1><div class="collection">${achievements().map(([ic,n,v,l,u])=>{const t=v>=l[2]?'gold':v>=l[1]?'silver':v>=l[0]?'bronze':'grey',next=t==='grey'?l[0]:t==='bronze'?l[1]:t==='silver'?l[2]:null;return`<div class="ach"><div class="row"><div class="icon ${t}">${ic}</div><div><b>${n}</b><br><small>${t==='grey'?'Locked':t[0].toUpperCase()+t.slice(1)}</small></div></div><div class="mile"><i class="${v>=l[0]?'on b':''}"></i><i class="${v>=l[1]?'on s':''}"></i><i class="${v>=l[2]?'on g':''}"></i></div><small>${next?`${v}/${next} ${u} · ${next-v} to next level`:`${v} ${u} · Gold achieved ✨`}</small></div>`}).join('')}</div><button class="primary wide" data-a="home">Back home</button></section>`);}
function tests(){return shell(`<section class="card"><div class="ey">ICAS Grade 2</div><h1>Subject tests</h1><div class="grid">${SUB.map(s=>`<button class="tile" data-s="${s}"><b>${s}</b><span>${FULL[s]} questions · full-length practice</span></button>`).join('')}</div></section>`);}
function progress(){return shell(`<section class="card"><div class="ey">Progress</div><h1>Learning at a glance</h1><div class="stats"><div class="stat"><b>${P.reviewQueue.length}</b><small>review</small></div><div class="stat"><b>${P.seenIds.length}</b><small>seen</small></div><div class="stat"><b>${P.attempts.length}</b><small>sessions</small></div></div></section>`);}
function parent(){const counts=Object.fromEntries(SUB.map(s=>[s,BANK.filter(q=>q.subject===s).length]));return shell(`<section class="card"><div class="ey">Parent</div><h1>Alistair at a glance</h1><p><b>Stability mode:</b> ICAS-authenticity reviewed static bank with cross-session construction rotation.</p>${SUB.map(s=>`<div class="path"><b>${s}</b> · ${counts[s]} authenticity-reviewed questions</div>`).join('')}<div class="path"><b>Novelty rotation</b> · ${new Set(P.recentFamilies||[]).size} recent constructions on cooldown</div><div class="path"><b>Practice selection</b> · last selection ${window.__AW_LAST_PICK_MS??'—'} ms</div><button class="primary wide" data-a="home">Back</button></section>`);}
function results(){return shell(`<section class="card"><div class="ey">Complete</div><h1>${Math.round(sess.result.score)}%</h1><h2>${sess.result.c} of ${sess.items.length} correct</h2><button class="primary wide" data-a="home">Done</button></section>`);}
function render(){A.innerHTML=S==='home'?home():S==='practice'?practice():S==='tests'?tests():S==='progress'?progress():S==='parent'?parent():S==='collection'?collection():results();}
A.addEventListener('click',e=>{const o=e.target.closest('[data-o]');if(o){sess.ans[sess.i]=o.dataset.o;return render()}const c=e.target.closest('[data-c]');if(c){sess.confidence[sess.i]=+c.dataset.c;sess.ask[sess.i]=0;sess.checked[sess.i]=1;return render()}const qn=e.target.closest('[data-q]');if(qn&&sess){stopRead();sess.i=+qn.dataset.q;return render()}const ss=e.target.closest('[data-s]');if(ss){stopRead();return start(subjectTest(ss.dataset.s),'icas-test',ss.dataset.s)}const b=e.target.closest('[data-a]');if(!b||b.disabled)return;const a=b.dataset.a;if(a==='read')return read();if(a==='flag'&&sess){sess.flagged[sess.i]=!sess.flagged[sess.i];return render()}if(a==='daily'){busy=true;render();requestAnimationFrame(()=>setTimeout(()=>start(dailyFast()),0));return}if(a==='check'){sess.ask[sess.i]=1;return render()}if(a==='next'){stopRead();if(sess.i<sess.items.length-1){sess.i++;return render()}return finish()}if(a==='back'&&sess.i){stopRead();sess.i--;return render()}stopRead();S=['tests','progress','parent','collection'].includes(a)?a:'home';render();});
window.__AW_RUNTIME_HEALTH={release:RELEASE,bank:BANK.length,subjects:Object.fromEntries(SUB.map(s=>[s,BANK.filter(q=>q.subject===s).length]))};render();
})();
