import { test, expect } from '@playwright/test';

test('feature-complete learner shell, iPad-safe historical papers and gated bonus challenge', async ({ page }) => {
  const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto('/');
  await expect(page.getByText('Hello Alistair')).toBeVisible();
  await expect(page.getByText('My Collection')).toBeVisible();
  await expect(page.locator('[data-a="progress"]')).toHaveCount(0);
  await expect(page.locator('.love')).toContainText('Made with');
  await expect(page.locator('.aw-heart')).toHaveText('♥');
  await expect(page.locator('.stats')).toHaveCount(0);
  await expect(page.locator('.aw-learning-line')).toBeVisible();
  await expect(page.locator('.aw-path-step.active')).toContainText('ICAS Y2');
  await expect(page.locator('.aw-path-step.locked')).toHaveCount(4);
  for(const label of ['ICAS Y2','ICAS Y3','NAPLAN Y3','ICAS Y4','OC'])await expect(page.locator('.aw-path-label',{hasText:label})).toBeVisible();
  await expect(page.getByText(/stable calibrated core/i)).toHaveCount(0);
  await expect(page.locator('[data-aw-bonus-card]')).toBeVisible();
  await expect(page.locator('[data-aw-bonus-card]')).toContainText('Locked');

  await page.locator('[data-a="parent"]').click();
  await expect(page.getByText('Parent insights')).toBeVisible();
  await expect(page.getByText('Subject performance')).toBeVisible();
  await expect(page.getByText('Subskill performance')).toBeVisible();
  await expect(page.getByText('Question supply',{exact:true})).toBeVisible();
  await expect(page.locator('.aw-overall-score')).toBeVisible();
  await expect(page.locator('.aw-subject-spectrum .aw-spectrum-row')).toHaveCount(3);
  await expect(page.locator('.aw-subject-panel')).toHaveCount(3);
  await expect(page.locator('.aw-subskill-spectrum .aw-spectrum-row')).not.toHaveCount(0);
  await expect(page.locator('.aw-spectrum-track').first()).toBeVisible();
  await expect(page.locator('.aw-unseen-grid > div')).toHaveCount(3);
  await page.locator('[data-aw-topup]').click();
  await expect(page.getByRole('button',{name:'Top-up requested'})).toBeVisible();
  await page.locator('[data-a="home"]').last().click();

  await page.locator('[data-a="tests"]').click();
  await expect(page.locator('.aw-form-subject')).toHaveCount(3);
  await expect(page.locator('[data-aw-original-year]')).toHaveCount(21);
  await expect(page.locator('[data-aw-form-id]')).toHaveCount(0);
  const english=page.locator('.aw-form-subject').filter({hasText:'English'});
  await expect(english).toContainText('35 questions · 35 min · 8 papers');
  const maths=page.locator('.aw-form-subject').filter({hasText:'Mathematics'});await expect(maths).toContainText('30 questions · 35 min · 8 papers');
  const science=page.locator('.aw-form-subject').filter({hasText:'Science'});await expect(science).toContainText('30 questions · 45 min · 5 papers');
  await english.locator('[data-aw-original-year="2013"]').click();
  const instruction=page.locator('.aw-instruction-overlay');
  await expect(instruction.getByText('Historical ICAS paper')).toBeVisible();
  await expect(instruction.getByRole('heading',{name:'2013 English'})).toBeVisible();
  await expect(instruction.getByText(/fully verified answer key/i)).toBeVisible();
  await page.locator('[data-aw-start-original]').click();
  await expect(page.locator('[data-aw-original-timer]')).toBeVisible();
  await expect(page.locator('iframe')).toHaveCount(0);
  await expect(page.locator('[data-aw-paper-frame]')).toBeVisible();
  await expect(page.locator('[data-aw-paper-canvas]')).toBeVisible();
  await expect(page.locator('[data-aw-page-prev]')).toBeVisible();
  await expect(page.locator('[data-aw-page-next]')).toBeVisible();
  const selector=page.locator('[data-aw-page-select]');
  await expect(selector).toBeVisible();await expect(selector).toHaveValue('1');
  await expect(page.locator('[data-aw-page-total]')).toHaveText('of 18');
  await expect(page.locator('[data-aw-page-label]')).toHaveText('Page 1 of 18');
  await expect(selector).toBeEnabled({timeout:15000});
  await expect(page.locator('[data-aw-page-next]')).toBeEnabled();
  await expect(page.locator('[data-aw-paper-status]')).toHaveText('');
  await selector.selectOption('2');
  await expect(selector).toHaveValue('2');
  await expect(page.locator('[data-aw-page-label]')).toHaveText('Page 2 of 18');
  await selector.selectOption('1');
  await expect(selector).toHaveValue('1');
  await expect(page.locator('[data-aw-page-label]')).toHaveText('Page 1 of 18');
  await expect(page.locator('[data-aw-page-prev]')).toBeDisabled();
  await expect(page.locator('[data-aw-answer-row]')).toHaveCount(35);
  await expect(page.locator('[data-aw-answer-text]')).toHaveCount(0);
  await page.locator('[data-aw-answer-choice="1"][data-value="D"]').click();
  await expect(page.locator('[data-aw-answer-choice="1"][data-value="D"]')).toHaveAttribute('aria-pressed','true');
  await expect(page.locator('.aw-running-exam').getByText(/correct/i)).toHaveCount(0);
  await page.locator('[data-aw-submit-original]').click();
  await expect(page.getByText('Historical formal test')).toBeVisible();
  await expect(page.getByRole('heading',{name:'3%'})).toBeVisible();
  await expect(page.getByText('1 of 35 correct')).toBeVisible();
  await expect(page.locator('.aw-answer-reference')).toHaveAttribute('href',/\/english\/2013-answers\.pdf/);
  const formalAttempt=await page.evaluate(()=>JSON.parse(localStorage.getItem('oc-ready-progress-v1')).attempts.at(-1));
  expect(formalAttempt.type).toBe('icas-original');expect(formalAttempt.subject).toBe('English');expect(formalAttempt.sourceYear).toBe(2013);expect(formalAttempt.score).toBe(3);expect(formalAttempt.correct).toBe(1);expect(formalAttempt.verified).toBe(true);expect(formalAttempt.durationSeconds).toBeGreaterThanOrEqual(0);expect(formalAttempt.timedOut).toBe(false);expect(formalAttempt.responses['1']).toBe('D');
  await page.locator('[data-aw-result-done]').click();
  await expect(page.locator('.aw-form-subject')).toHaveCount(3);
  const englishAgain=page.locator('.aw-form-subject').filter({hasText:'English'});
  await englishAgain.locator('[data-aw-original-year="2020"]').click();await page.locator('[data-aw-start-original]').click();
  await expect(page.locator('[data-aw-page-select]')).toBeEnabled({timeout:15000});
  await expect(page.locator('[data-aw-answer-row="31"] small')).toContainText('Select all');
  await page.locator('[data-aw-answer-choice="31"][data-value="B"]').click();await page.locator('[data-aw-answer-choice="31"][data-value="C"]').click();
  await expect(page.locator('[data-aw-answer-choice="31"][aria-pressed="true"]')).toHaveCount(2);
  page.once('dialog',d=>d.accept());await page.locator('[data-aw-exam-exit]').click();await expect(page.locator('[data-aw-exam-overlay]')).toHaveCount(0);

  const perfectDate=new Date().toISOString();
  await page.evaluate(({perfectDate})=>localStorage.setItem('oc-ready-progress-v1',JSON.stringify({attempts:[{date:perfectDate,score:100,subject:'Daily',type:'practice'}],seenIds:[],reviewQueue:[],recentFamilies:[],xp:0,streak:1,skillStats:{},lastActiveDate:null})),{perfectDate});
  await page.reload();await expect(page.locator('[data-aw-bonus-card]')).toContainText('Unlocked');await expect(page.locator('[data-aw-bonus-start]')).toBeVisible();
  const coreBefore=await page.evaluate(()=>JSON.parse(localStorage.getItem('oc-ready-progress-v1')).attempts.length);await page.locator('[data-aw-bonus-start]').click();
  await expect(page.getByText(/Question 1 of 1/i)).toBeVisible();await expect(page.getByText(/Bonus Challenge/i).first()).toBeVisible();
  const selected=await page.evaluate(()=>{const stem=document.querySelector('.question-pane .q')?.textContent||'';const q=(window.AW_BONUS_BANK||[]).find(x=>x.question===stem);return q?{answer:q.answer,kind:q.kind,difficulty:q.difficulty,stimulus:!!q.stimulus}:null});
  expect(selected).toBeTruthy();expect(selected.difficulty).toBe(5);expect(selected.answer).toMatch(/^[ABCD]$/);
  if(selected.kind==='visual'){await expect(page.locator('.stimulus-visual')).toBeVisible();await expect(page.locator('.testworkspace')).toHaveClass(/aw-visual-stimulus/)}else if(selected.stimulus){await expect(page.locator('.testworkspace')).toHaveClass(/aw-question-only/);await expect(page.locator('.aw-inline-stimulus')).toBeVisible()}
  await page.locator(`[data-o="${selected.answer}"]`).click();await page.locator('[data-a="check"]').click();await page.locator('[data-c="3"]').click();await page.locator('[data-a="next"]').click();
  await expect(page.getByText('Challenge complete!')).toBeVisible();const state=await page.evaluate(()=>({core:JSON.parse(localStorage.getItem('oc-ready-progress-v1')),bonus:JSON.parse(localStorage.getItem('awenture-bonus-v1'))}));
  expect(state.core.attempts.length).toBe(coreBefore);expect(state.bonus.streak).toBe(1);expect(state.bonus.attempts).toHaveLength(1);expect(state.bonus.attempts[0].correct).toBe(true);
  await page.locator('[data-a="home"]').last().click();await expect(page.locator('[data-aw-bonus-card]')).toContainText('Complete');await page.locator('[data-a="collection"]').click();
  await expect(page.getByText('6 achievements')).toBeVisible();await expect(page.locator('.aw-ach')).toHaveCount(6);
  for(const removed of ['Comeback Kid','English Explorer','Maths Master','Science Star','Visual Detective'])await expect(page.getByText(removed,{exact:true})).toHaveCount(0);
  await expect(page.getByText('Bonus Challenger',{exact:true})).toBeVisible();await expect(page.getByText(/Gold in the main collection represents sustained effort/i)).toBeVisible();expect(errors).toEqual([]);
});