import { test, expect } from '@playwright/test';

test('historical paper viewer supports iPad-safe zoom and horizontal panning', async ({ page }) => {
  await page.goto('/');
  await page.locator('[data-a="tests"]').click();
  const english=page.locator('.aw-form-subject').filter({hasText:'English'});
  await english.locator('[data-aw-original-year="2013"]').click();
  await page.locator('[data-aw-start-original]').click();
  const selector=page.locator('[data-aw-page-select]');
  await expect(selector).toBeEnabled({timeout:15000});
  const zoomIn=page.locator('[data-aw-zoom-in]');
  const zoomOut=page.locator('[data-aw-zoom-out]');
  const panLeft=page.locator('[data-aw-pan-left]');
  const panRight=page.locator('[data-aw-pan-right]');
  const zoomLabel=page.locator('[data-aw-zoom-label]');
  await expect(zoomIn).toBeVisible();
  await expect(zoomOut).toBeVisible();
  await expect(panLeft).toBeVisible();
  await expect(panRight).toBeVisible();
  await zoomIn.click();
  await expect(zoomLabel).toHaveText('115%');
  await page.waitForTimeout(250);
  await zoomIn.click();
  await expect(zoomLabel).toHaveText('130%');
  const before=await page.locator('[data-aw-paper-frame]').evaluate(el=>({left:el.scrollLeft,width:el.clientWidth,scrollWidth:el.scrollWidth,touch:getComputedStyle(el).touchAction}));
  expect(before.scrollWidth).toBeGreaterThan(before.width);
  expect(before.touch).toContain('pan-x');
  await panRight.click();
  await page.waitForTimeout(350);
  const after=await page.locator('[data-aw-paper-frame]').evaluate(el=>el.scrollLeft);
  expect(after).toBeGreaterThan(before.left);
  await panLeft.click();
  await page.waitForTimeout(350);
  const back=await page.locator('[data-aw-paper-frame]').evaluate(el=>el.scrollLeft);
  expect(back).toBeLessThan(after);
  await zoomOut.click();
  await expect(zoomLabel).toHaveText('115%');
  page.once('dialog',d=>d.accept());
  await page.locator('[data-aw-exam-exit]').click();
});
