import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const m=JSON.parse(fs.readFileSync(path.join(root,'baseline/manifest.json'),'utf8'));
let b64=''; for(let i=1;i<=m.parts;i++) b64+=fs.readFileSync(path.join(root,`baseline/v6.9.0.part${String(i).padStart(2,'0')}`),'utf8').trim();
const html=zlib.gunzipSync(Buffer.from(b64,'base64'));
const sha=crypto.createHash('sha256').update(html).digest('hex');
if(sha!==m.sha256) throw new Error(`AWenture baseline integrity failure: ${sha}`);
if(html.length!==m.decodedBytes) throw new Error(`AWenture baseline size mismatch: ${html.length}`);
fs.rmSync(path.join(root,'dist'),{recursive:true,force:true}); fs.mkdirSync(path.join(root,'dist'));
fs.writeFileSync(path.join(root,'dist/index.html'),html);
console.log(JSON.stringify({release:m.release,sha256:sha,bytes:html.length,output:'dist/index.html'}));
