import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const file=path.join(root,'dist/index.html');
const spelling=JSON.parse(fs.readFileSync(path.join(root,'bank/v6.16.0-spelling.json'),'utf8'));
if(spelling.length<30)throw new Error('Spelling bank unexpectedly small');
for(const q of spelling){
  if(q.subject!=='Spelling'||q.kind!=='audio'||!q.audioWord||!q.audioSentence||!Array.isArray(q.options)||q.options.length!==4||!'ABCD'.includes(q.answer))throw new Error('Invalid spelling question '+q.id);
  if(q.options['ABCD'.indexOf(q.answer)]!==q.audioWord)throw new Error('Spelling answer/audio mismatch '+q.id);
  if(new Set(q.options.map(x=>x.toLowerCase())).size!==4)throw new Error('Duplicate spelling options '+q.id);
}
let html=fs.readFileSync(file,'utf8').replaceAll('6.15.3','6.16.0').replaceAll('61530','61600');
const runtimeMarker="\n\n(()=>{'use strict';\nconst A=";
if(!html.includes(runtimeMarker))throw new Error('Core runtime injection marker not found');
html=html.replace(runtimeMarker,`\n\n/* v6.16.0 AWenture-generated audio spelling bank, calibrated to ICAS Year 2 level; not an original ICAS question set */\nwindow.AW_BANK.push(...${JSON.stringify(spelling)});${runtimeMarker}`);
const readMarker="const q=sess.items[sess.i],u=new SpeechSynthesisUtterance([q.stimulus,q.question,...q.options.map((o,i)=>L[i]+'. '+o)].filter(Boolean).join('. ')),vs=";
const readReplacement="const q=sess.items[sess.i],spoken=q.subject==='Spelling'&&q.audioWord?[q.audioWord,q.audioSentence,q.audioWord]:[q.stimulus,q.question,...q.options.map((o,i)=>L[i]+'. '+o)],u=new SpeechSynthesisUtterance(spoken.filter(Boolean).join('. ')),vs=";
if(!html.includes(readMarker))throw new Error('Speech synthesis marker not found');
html=html.replace(readMarker,readReplacement);
if(!html.includes('u.rate=.92;u.pitch=1.04;'))throw new Error('Speech rate marker not found');
html=html.replace('u.rate=.92;u.pitch=1.04;',"u.rate=q.subject==='Spelling'?.82:.92;u.pitch=1.04;");
const stimulusMarker='function stimulus(q){const text=';
if(!html.includes(stimulusMarker))throw new Error('Stimulus marker not found');
html=html.replace(stimulusMarker,"function stimulus(q){if(q.subject==='Spelling'&&q.audioWord)return '<div class=\"stimulus-empty aw-spelling-listen\"><span>🔊 Tap “Listen to word” above, then choose the correct spelling.</span></div>';const text=");
const readButton="<button class=\"iconbtn\" data-a=\"read\">${speaking?'■ Stop':'🔊 Read'}</button>";
const spellingButton="<button class=\"iconbtn\" data-a=\"read\">${speaking?'■ Stop':q.subject==='Spelling'?'🔊 Listen to word':'🔊 Read'}</button>";
if(!html.includes(readButton))throw new Error('Read button marker not found');
html=html.replace(readButton,spellingButton);
const dailyMarker='window.__AW_LAST_PICK_MS=Math.round((performance.now()-t0)*100)/100;return shuffle(out.slice(0,12),sd+173);';
const dailyReplacement=`const spellingPool=BANK.filter(q=>q.subject==='Spelling'&&q.kind==='audio');
  const spellingCandidates=[...shuffle(spellingPool.filter(q=>!seen.has(q.id)&&!recent.has(familyKey(q))),sd+211),...shuffle(spellingPool.filter(q=>!seen.has(q.id)&&recent.has(familyKey(q))),sd+223),...shuffle(spellingPool.filter(q=>seen.has(q.id)),sd+227)];
  for(const q of spellingCandidates){if(out.filter(x=>x.subject==='Spelling').length===3)break;const f=familyKey(q);if(out.some(x=>x.id===q.id)||used.has(f))continue;out.push(q);used.add(f)}
  if(out.filter(x=>x.subject==='Spelling').length!==3)throw new Error('AWenture spelling pool could not supply 3 Daily Practice questions');
  window.__AW_LAST_PICK_MS=Math.round((performance.now()-t0)*100)/100;return shuffle(out.slice(0,15),sd+173);`;
if(!html.includes(dailyMarker))throw new Error('Daily Practice completion marker not found');
html=html.replace(dailyMarker,dailyReplacement);
html=html.replaceAll("Object.fromEntries(SUB.map(s=>[s,BANK.filter(q=>q.subject===s).length]))","Object.fromEntries([...SUB,'Spelling'].map(s=>[s,BANK.filter(q=>q.subject===s).length]))");
fs.writeFileSync(file,html);
console.log(JSON.stringify({release:'6.16.0',spellingBank:spelling.length,dailyQuestionCount:15,dailyMix:{English:4,Mathematics:4,Science:4,Spelling:3},audioMode:'WORD_SENTENCE_WORD',tts:'BROWSER_SPEECH_SYNTHESIS',provenance:'AWENTURE_GENERATED_ICAS_Y2_CALIBRATED'}));
