import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const file=path.join(root,'dist/index.html');
let html=fs.readFileSync(file,'utf8');
html=html.replaceAll('6.14.1','6.15.0').replaceAll('61410','61500');
const head='<link rel="icon" type="image/png" href="/awenture-logo.png?v=61500"><link rel="apple-touch-icon" href="/awenture-logo.png?v=61500"><link rel="stylesheet" href="/brand.css?v=61500"><link rel="stylesheet" href="/v615.css?v=61500>';
const fixedHead=head.replace('v=61500>','v=61500">');
if(!html.includes('/brand.css?v=61500'))html=html.replace('</head>',fixedHead+'</head>');
const scripts='<script src="/dynamic-bank.js?v=61500" defer></script><script src="/brand.js?v=61500" defer></script><script src="/v615-parent.js?v=61500" defer></script>';
if(!html.includes('/dynamic-bank.js?v=61500'))html=html.replace('</body>',scripts+'</body>');
for(const f of ['brand.css','v615.css'])fs.copyFileSync(path.join(root,'ui',f),path.join(root,'dist',f));
for(const f of ['dynamic-bank.js','brand.js','v615-parent.js'])fs.copyFileSync(path.join(root,'ui',f),path.join(root,'dist',f));
fs.copyFileSync(path.join(root,'assets/awenture-logo.png'),path.join(root,'dist/awenture-logo.png'));
for(const required of ['aw-dynamic-bank-1','dual-pass-released'])if(!fs.readFileSync(path.join(root,'ui/dynamic-bank.js'),'utf8').includes(required))throw new Error(`Dynamic bank runtime missing: ${required}`);
for(const required of ['aw-brand-logo','aw-brand-1'])if(!fs.readFileSync(path.join(root,'ui/brand.js'),'utf8').includes(required))throw new Error(`Brand runtime missing: ${required}`);
for(const required of ['subskillsCollapsedByDefault','aw-subskill-details'])if(!fs.readFileSync(path.join(root,'ui/v615-parent.js'),'utf8').includes(required))throw new Error(`Parent collapse runtime missing: ${required}`);
fs.writeFileSync(file,html);
console.log(JSON.stringify({release:'6.15.0',releasedPracticeBank:'DUAL_PASS_AUTO_SYNC',brand:'AW_EMBLEM',parentSubskills:'COLLAPSED_BY_DEFAULT'}));
