import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const htmlPath=path.join(root,'dist/index.html');
const formalPath=path.join(root,'dist/formal-tests.js');
const cssPath=path.join(root,'dist/formal-tests.css');
let html=fs.readFileSync(htmlPath,'utf8');
html=html.replaceAll('6.13.1.1','6.13.1.2').replaceAll('v=61311','v=61312');
fs.writeFileSync(htmlPath,html);
let formal=fs.readFileSync(formalPath,'utf8');
formal=formal.replaceAll('6.13.1.1','6.13.1.2');
const zoomMarkup='<span class="aw-zoom-controls"><button type="button" data-aw-zoom-out aria-label="Zoom out">−</button><span data-aw-zoom-label>100%</span><button type="button" data-aw-zoom-in aria-label="Zoom in">+</button></span>';
const newMarkup=zoomMarkup+'<span class="aw-pan-controls"><button type="button" data-aw-pan-left aria-label="Pan paper left">← Pan</button><button type="button" data-aw-pan-right aria-label="Pan paper right">Pan →</button></span>';
if(!formal.includes(zoomMarkup))throw new Error('Missing zoom toolbar markup');
formal=formal.replace(zoomMarkup,newMarkup);
const bindAnchor="bindPager('[data-aw-zoom-in]',()=>changeZoom(.15));const stage=qs('[data-aw-paper-frame]');";
const bindReplacement="bindPager('[data-aw-zoom-in]',()=>changeZoom(.15));function panPaper(dir){const s=qs('[data-aw-paper-frame]');if(!s||!active||!active.pdfDoc)return;const amount=Math.max(180,Math.round(s.clientWidth*.72));s.scrollBy({left:dir*amount,behavior:'smooth'})}bindPager('[data-aw-pan-left]',()=>panPaper(-1));bindPager('[data-aw-pan-right]',()=>panPaper(1));const stage=qs('[data-aw-paper-frame]');";
if(!formal.includes(bindAnchor))throw new Error('Missing viewer binding anchor');
formal=formal.replace(bindAnchor,bindReplacement);
formal=formal.replace('Swipe left or right to change pages','At Fit width, swipe changes pages. After zooming in, drag horizontally or use Pan ← / → to inspect a wide double-spread.');
formal+='\n/* v6.13.1.2 wide-paper navigation */\n';
fs.writeFileSync(formalPath,formal);
fs.appendFileSync(cssPath,`\n/* v6.13.1.2 wide double-spread navigation */\n.aw-paper-stage{touch-action:pan-x pan-y pinch-zoom!important;scroll-behavior:smooth}.aw-pan-controls{display:flex;align-items:center;gap:5px}.aw-pan-controls button{min-width:70px}.aw-running-exam .aw-zoom-controls{display:flex!important}@media(max-width:900px){.aw-pan-controls{grid-column:1/-1;justify-content:center}.aw-running-exam .aw-zoom-controls{grid-column:1/-1;justify-content:center}}@media(max-width:700px){.aw-running-exam .aw-zoom-controls,.aw-pan-controls{display:flex!important}.aw-zoom-controls,.aw-pan-controls{grid-column:1/-1}.aw-paper-swipe-hint{display:block!important;padding:0 8px;line-height:1.35}}\n`);
console.log(JSON.stringify({releaseOverlay:'6.13.1.2',widePaperNavigation:'PASS'}));
