import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const htmlPath=path.join(root,'dist/index.html');
const formalPath=path.join(root,'dist/formal-tests.js');
const cssPath=path.join(root,'dist/formal-tests.css');

let html=fs.readFileSync(htmlPath,'utf8');
html=html.replaceAll('6.13.1.2','6.13.1.3').replaceAll('v=61312','v=61313');
fs.writeFileSync(htmlPath,html);

let formal=fs.readFileSync(formalPath,'utf8');
formal=formal.replaceAll('6.13.1.2','6.13.1.3');

const oldRender="async function renderPaperPage(){if(!active?.pdfDoc)return;const serial=++renderSerial,pageNo=active.page||1,stage=qs('[data-aw-paper-frame]'),canvas=qs('[data-aw-paper-canvas]');if(!stage||!canvas)return;viewerStatus(`Loading page ${pageNo}…`);try{const page=await active.pdfDoc.getPage(pageNo);if(serial!==renderSerial||!active)return;const base=page.getViewport({scale:1}),available=Math.max(280,(stage.clientWidth||700)-28),cssScale=Math.max(.45,Math.min(2.4,(available/base.width)*(active.zoom||1))),dpr=Math.min(window.devicePixelRatio||1,2),view=page.getViewport({scale:cssScale*dpr});canvas.width=Math.ceil(view.width);canvas.height=Math.ceil(view.height);canvas.style.width=`${Math.round(base.width*cssScale)}px`;canvas.style.height=`${Math.round(base.height*cssScale)}px`;const ctx=canvas.getContext('2d',{alpha:false});ctx.save();ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore();await page.render({canvasContext:ctx,viewport:view}).promise;if(serial!==renderSerial)return;viewerStatus('');syncViewerControls();}catch(err){if(serial===renderSerial)viewerStatus('Unable to render this page. Please exit and reopen the paper.',true)}}";
const newRender="async function renderPaperPage(retry=0){if(!active?.pdfDoc)return;const serial=++renderSerial,pageNo=active.page||1,stage=qs('[data-aw-paper-frame]'),canvas=qs('[data-aw-paper-canvas]');if(!stage||!canvas)return;try{if(active.renderTask){active.renderTask.cancel();active.renderTask=null}}catch(_){}viewerStatus(`Loading page ${pageNo}…`);try{const page=await active.pdfDoc.getPage(pageNo);if(serial!==renderSerial||!active)return;const base=page.getViewport({scale:1}),available=Math.max(280,(stage.clientWidth||700)-28),cssScale=Math.max(.45,Math.min(2.4,(available/base.width)*(active.zoom||1))),dpr=Math.min(window.devicePixelRatio||1,2),view=page.getViewport({scale:cssScale*dpr});const buffer=document.createElement('canvas');buffer.width=Math.ceil(view.width);buffer.height=Math.ceil(view.height);const ctx=buffer.getContext('2d',{alpha:false});ctx.save();ctx.fillStyle='#fff';ctx.fillRect(0,0,buffer.width,buffer.height);ctx.restore();const task=page.render({canvasContext:ctx,viewport:view});active.renderTask=task;await task.promise;if(serial!==renderSerial||!active)return;active.renderTask=null;canvas.width=buffer.width;canvas.height=buffer.height;canvas.style.width=`${Math.round(base.width*cssScale)}px`;canvas.style.height=`${Math.round(base.height*cssScale)}px`;canvas.style.transform='';const visible=canvas.getContext('2d',{alpha:false});visible.save();visible.fillStyle='#fff';visible.fillRect(0,0,canvas.width,canvas.height);visible.drawImage(buffer,0,0);visible.restore();stage.scrollLeft=Math.min(stage.scrollLeft,Math.max(0,stage.scrollWidth-stage.clientWidth));viewerStatus('');syncViewerControls();}catch(err){if(err?.name==='RenderingCancelledException'||serial!==renderSerial)return;if(retry<1){await new Promise(r=>setTimeout(r,80));if(serial===renderSerial&&active)renderPaperPage(1);return}if(serial===renderSerial)viewerStatus('Unable to render this page. Please try this page again.',true)}}";
if(!formal.includes(oldRender))throw new Error('Missing original PDF render function');
formal=formal.replace(oldRender,newRender);

const oldTouch="const stage=qs('[data-aw-paper-frame]');let touchStartX=null,touchStartY=null;if(stage){stage.addEventListener('touchstart',e=>{const t=e.touches[0];touchStartX=t.clientX;touchStartY=t.clientY},{passive:true});stage.addEventListener('touchend',e=>{if(touchStartX==null||!active||active.zoom>1.1)return;const t=e.changedTouches[0],dx=t.clientX-touchStartX,dy=t.clientY-touchStartY;touchStartX=touchStartY=null;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy)*1.25)changePage(dx<0?1:-1)},{passive:true})}";
const newTouch="const stage=qs('[data-aw-paper-frame]');let touchStartX=null,touchStartY=null,pinchStartDistance=0,pinchStartZoom=1,pinchTargetZoom=1,gestureStartZoom=1;const paperCanvas=()=>qs('[data-aw-paper-canvas]');const clampZoom=z=>Math.max(.75,Math.min(2,Math.round(z*100)/100));const touchDistance=e=>{if(!e.touches||e.touches.length<2)return 0;const a=e.touches[0],b=e.touches[1];return Math.hypot(b.clientX-a.clientX,b.clientY-a.clientY)};const previewPinch=z=>{if(!active)return;pinchTargetZoom=clampZoom(z);const c=paperCanvas();if(c)c.style.transform=`scale(${pinchTargetZoom/(active.zoom||1)})`};const commitPinch=()=>{if(!active)return;const c=paperCanvas();if(c)c.style.transform='';if(Math.abs(pinchTargetZoom-(active.zoom||1))>.01){active.zoom=pinchTargetZoom;syncViewerControls();renderPaperPage()}pinchStartDistance=0};if(stage){stage.dataset.awTouchGestures='pinch-pan';stage.addEventListener('touchstart',e=>{if(e.touches.length>=2&&active){pinchStartDistance=touchDistance(e);pinchStartZoom=active.zoom||1;pinchTargetZoom=pinchStartZoom;touchStartX=touchStartY=null;return}const t=e.touches[0];touchStartX=t.clientX;touchStartY=t.clientY},{passive:true});stage.addEventListener('touchmove',e=>{if(e.touches.length>=2&&pinchStartDistance&&active){e.preventDefault();const d=touchDistance(e);if(d)previewPinch(pinchStartZoom*d/pinchStartDistance)}},{passive:false});stage.addEventListener('touchend',e=>{if(pinchStartDistance){e.preventDefault();commitPinch();return}if(touchStartX==null||!active||active.zoom>1.1)return;const t=e.changedTouches[0],dx=t.clientX-touchStartX,dy=t.clientY-touchStartY;touchStartX=touchStartY=null;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy)*1.25)changePage(dx<0?1:-1)},{passive:false});stage.addEventListener('gesturestart',e=>{if(!active)return;e.preventDefault();gestureStartZoom=active.zoom||1;pinchTargetZoom=gestureStartZoom},{passive:false});stage.addEventListener('gesturechange',e=>{if(!active)return;e.preventDefault();previewPinch(gestureStartZoom*(e.scale||1))},{passive:false});stage.addEventListener('gestureend',e=>{if(!active)return;e.preventDefault();commitPinch()},{passive:false})}";
if(!formal.includes(oldTouch))throw new Error('Missing historical touch block');
formal=formal.replace(oldTouch,newTouch);
formal=formal.replace('At Fit width, swipe changes pages. After zooming in, drag horizontally or use Pan ← / → to inspect a wide double-spread.','On iPhone/iPad, pinch to zoom and drag to pan. At Fit width, a horizontal swipe changes pages.');
formal+='\n/* v6.13.1.3 atomic PDF rendering + native touch pinch/pan */\n';
fs.writeFileSync(formalPath,formal);

fs.appendFileSync(cssPath,`\n/* v6.13.1.3 compact responsive viewer controls and touch-first mobile canvas */\n.aw-paper-toolbar{display:flex!important;align-items:center;justify-content:center;gap:7px;flex-wrap:nowrap!important;padding:8px 10px}.aw-page-select-wrap,.aw-zoom-controls,.aw-pan-controls{display:flex;align-items:center;gap:5px;flex:0 0 auto}.aw-paper-toolbar>button{flex:0 0 auto}.aw-paper-stage{touch-action:pan-x pan-y!important;overscroll-behavior:contain;-webkit-overflow-scrolling:touch;scroll-behavior:smooth}.aw-paper-stage canvas{transform-origin:center center;transition:transform .05s linear}.aw-paper-pane{min-width:0}.aw-paper-swipe-hint{margin:4px 0 0}@media(max-width:900px){.aw-paper-toolbar{gap:5px;padding:6px}.aw-paper-toolbar button{min-height:38px;padding:6px 9px}.aw-page-select-wrap{font-size:11px}.aw-page-select-wrap select{min-height:38px;min-width:54px}.aw-paper-stage{height:clamp(430px,62dvh,760px)!important;max-height:calc(100dvh - 190px)}}@media(hover:none) and (pointer:coarse){.aw-running-exam .aw-zoom-controls,.aw-running-exam .aw-pan-controls{display:none!important}.aw-paper-toolbar{justify-content:space-between}.aw-paper-swipe-hint{display:block!important}}@media(max-width:700px){.aw-paper-toolbar{justify-content:space-between;gap:4px}.aw-paper-toolbar>button{font-size:12px;padding:5px 7px}.aw-page-select-wrap span:first-child{display:none}.aw-page-select-wrap select{min-width:52px;min-height:36px}.aw-paper-stage{height:clamp(420px,68dvh,760px)!important;max-height:calc(100dvh - 154px);min-height:360px}.aw-paper-swipe-hint{display:block!important;font-size:11px;line-height:1.25;padding:0 6px}.aw-paper-pane{height:auto}}@media(max-width:430px){.aw-paper-toolbar{padding:5px 3px}.aw-paper-toolbar>button{font-size:11px;padding:4px 6px}.aw-page-select-wrap{gap:3px}.aw-page-select-wrap select{min-width:48px;padding-left:5px;padding-right:18px}.aw-paper-stage{height:calc(100dvh - 148px)!important;min-height:350px}}\n`);
console.log(JSON.stringify({releaseOverlay:'6.13.1.3',atomicPdfRender:'PASS',touchPinchPan:'PASS',compactToolbar:'PASS'}));
