(()=>{
'use strict';
/* v6.18.2 invisible stage-aware skill selector for Years 2-4 + generation-safe Year 2 coverage targeting. No child-facing UI. */
const SUBJECT_PREFIX={English:'ENG',Mathematics:'MATH',Science:'SCI',Spelling:'SPELL'};
const UNSAFE_VISUAL_IDS=new Set(['M09','M18','M19','M23','M26','M31']);
const STAGE_GRADES=Object.freeze({'icas-y2':2,'icas-y3':3,'naplan-y3':3,'icas-y4':4,'oc-prep':4});
const ACTIVE_STAGES=Object.freeze(['icas-y2','icas-y3','naplan-y3','icas-y4']);
const ACTIVE_STAGE_SET=new Set(ACTIVE_STAGES);
const TARGETS={
English:[['Y2.ENG.LITERACY.SEQUENCE_AND_RETELL','Sequence and retell',0,['sequence','order','route','procedure']],['Y2.ENG.LITERACY.INFERENCE','Inference from evidence',1,['infer','inference','evidence','feeling']],['Y2.ENG.LANGUAGE.VOCABULARY_IN_CONTEXT','Vocabulary in context',2,['vocab','meaning','context','synonym']],['Y2.ENG.LANGUAGE.PRONOUNS_AND_REFERENCE','Pronouns and reference',3,['pronoun','reference']],['Y2.ENG.LANGUAGE.PUNCTUATION_AND_CAPITALISATION','Punctuation and capitalisation',4,['punctuation','capital']],['Y2.ENG.LITERACY.MAIN_IDEA_AND_KEY_DETAILS','Main idea and key details',5,['main idea','key detail']],['Y2.ENG.LITERACY.FACT_AND_OPINION','Fact and opinion',6,['fact','opinion']],['Y2.ENG.LITERACY.PROCEDURAL_TEXTS','Procedural texts',7,['procedure','instruction']],['Y2.ENG.LANGUAGE.WORD_RELATIONSHIPS','Word relationships',8,['antonym','opposite','word relationship']],['Y2.ENG.LITERACY.TEXT_PURPOSE_AND_AUDIENCE','Text purpose and audience',9,['purpose','audience','heading']],['Y2.ENG.LITERACY.DIALOGUE_INFERENCE','Dialogue inference',10,['dialogue','reply']],['Y2.ENG.LITERACY.COMPARE_SOURCES','Compare sources',11,['compare','two source','both notices']]],
Mathematics:[['Y2.MATH.NUMBER.PLACE_VALUE','Place value',0,['place value','number representation']],['Y2.MATH.NUMBER.MONEY_VALUES_AND_COMBINATIONS','Money values and combinations',1,['money','coin']],['Y2.MATH.NUMBER.DIVISION_AS_SHARING','Division as sharing',2,['division','sharing']],['Y2.MATH.NUMBER.FRACTIONS_OF_WHOLES_AND_COLLECTIONS','Fractions of collections',3,['fraction','half','quarter']],['Y2.MATH.MEASUREMENT.COMPARE_AND_MEASURE_LENGTH','Length and metric units',4,['length','metre','centimetre','ruler']],['Y2.MATH.SPACE.2D_SHAPES_AND_PROPERTIES','2D shapes and properties',5,['shape','2d']],['Y2.MATH.ALGEBRA.NUMBER_SENTENCES_AND_MISSING_VALUES','Number sentences and missing values',6,['missing','inverse','number sentence']],['Y2.MATH.MEASUREMENT.DURATION_AND_CALENDARS','Calendars and duration',7,['calendar','day','date','time']],['Y2.MATH.NUMBER.MULTIPLICATION_AS_GROUPS','Multiplication as groups',8,['multiplication','array','groups']],['Y2.MATH.STATISTICS.READ_TABLES_AND_PICTURE_GRAPHS','Read tables and data displays',9,['table','graph','data']],['Y2.MATH.SPACE.SYMMETRY_AND_TRANSFORMATIONS','Symmetry and transformations',10,['symmetry','turn','rotation']],['Y2.MATH.MEASUREMENT.COMPARE_MASS','Compare mass',11,['mass','weight','balance']]],
Science:[['Y2.SCI.UNDERSTANDING.EARTH_SKY_AND_WEATHER_PATTERNS','Earth, sky and weather patterns',0,['shadow','sun','weather','earth']],['Y2.SCI.UNDERSTANDING.MATERIALS_AND_PROPERTIES','Materials and properties',1,['material','magnet','magnetic']],['Y2.SCI.UNDERSTANDING.LIFE_CYCLES_AND_CHANGE','Life cycles and change',2,['life cycle','cycle']],['Y2.SCI.UNDERSTANDING.LIVING_THINGS_NEEDS_AND_FEATURES','Living things: features and needs',3,['body feature','adaptation','living']],['Y2.SCI.UNDERSTANDING.LIGHT_SOUND_AND_HEAT_OBSERVATIONS','Sound and vibration',4,['sound','vibration']],['Y2.SCI.INQUIRY.COMPARE_RESULTS_WITH_PREDICTIONS','Fair testing',5,['fair test','variable','investigat']],['Y2.SCI.UNDERSTANDING.CHANGES_TO_MATERIALS','Changes to materials',6,['dissolv','change material']],['Y2.SCI.INQUIRY.OBSERVE_AND_MEASURE','Observations as evidence',7,['observation','evidence']],['Y2.SCI.UNDERSTANDING.EARTH_ROTATION_DAY_NIGHT','Day and night',8,['day and night','earth rotation']],['Y2.SCI.UNDERSTANDING.LIGHT_TRANSPARENCY','Light and transparency',9,['transparent','light pass']],['Y2.SCI.UNDERSTANDING.FOOD_CHAINS','Food chains',10,['food chain']],['Y2.SCI.INQUIRY.OBSERVE_AND_MEASURE_WEATHER','Weather measurement',11,['rain gauge','weather instrument']]]};
const norm=x=>String(x??'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'other';
const fnv=s=>{let h=2166136261>>>0;for(let i=0;i<String(s).length;i++){h^=String(s).charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const stageOf=q=>String(q?.stage||q?.learningStage||q?.frameworkStage||'icas-y2');
const gradeOf=q=>STAGE_GRADES[stageOf(q)]||2;
const activeStage=q=>ACTIVE_STAGE_SET.has(stageOf(q));
const skillName=q=>String(q?.subskill||q?.skill||q?.strand||'Other').trim()||'Other';
const explicitTarget=q=>String(q?.skillId||q?.quality?.skillId||q?.quality?.focus||'').match(/^(Y[234]\.[A-Z0-9_.]+)/)?.[1]||'';
const skillId=q=>explicitTarget(q)||`Y${gradeOf(q)}.${SUBJECT_PREFIX[q?.subject]||'GEN'}.${norm(skillName(q)).toUpperCase().replaceAll('-','_')}`;
const family=(q,helpers)=>{try{return helpers?.familyKey?helpers.familyKey(q):String(q?.family||q?.id||'')}catch(_){return String(q?.family||q?.id||'')}};
const searchText=q=>`${q?.skill||''} ${q?.subskill||''} ${q?.family||''} ${q?.question||''}`.toLowerCase();
const stageProfile=arr=>{const out={};for(const q of arr||[]){const s=stageOf(q);out[s]=(out[s]||0)+1}return out};
const sameProfile=(a,b)=>{const keys=new Set([...Object.keys(a),...Object.keys(b)]);for(const k of keys)if((a[k]||0)!==(b[k]||0))return false;return true};
function statFor(q,p){const stats=p?.skillStats&&typeof p.skillStats==='object'?p.skillStats:{};const raw=stats[`${q.subject}|${skillName(q)}`]||stats[skillId(q)]||null;const a=Number(raw?.a)||0,c=Number(raw?.c)||0;return {a,c,accuracy:a?c/a:null}}
function score(q,p,seen,recent,helpers){const s=statFor(q,p),f=family(q,helpers);let n=0;if(!seen.has(q.id))n+=120;else n-=35;if(s.a===0)n+=70;else{n+=(1-s.accuracy)*65;n+=Math.max(0,18-Math.min(18,s.a*3))}if(recent.has(f))n-=55;if(q.kind==='visual')n+=2;return n}
function eligible(q,slot,chosenFamilies,chosenIds,seen,recent,helpers){if(!q||q.subject!==slot.subject||q.kind!==slot.kind||stageOf(q)!==stageOf(slot))return false;if(UNSAFE_VISUAL_IDS.has(q.id)||chosenIds.has(q.id))return false;if(!seen.has(slot.id)&&seen.has(q.id))return false;const f=family(q,helpers),slotFamily=family(slot,helpers);if(chosenFamilies.has(f))return false;if(!recent.has(slotFamily)&&recent.has(f))return false;return true}
function rebalance(existing,bank,p,sd,helpers={}){try{if(!Array.isArray(existing)||existing.length!==15||!Array.isArray(bank))return existing;const expected={English:4,Mathematics:4,Science:4,Spelling:3};for(const [subject,count] of Object.entries(expected))if(existing.filter(q=>q?.subject===subject).length!==count)return existing;const originalStages=stageProfile(existing),seen=new Set(Array.isArray(p?.seenIds)?p.seenIds:[]),recent=helpers?.recent instanceof Set?helpers.recent:new Set(),chosen=[],chosenIds=new Set(),chosenFamilies=new Set();for(const slot of existing){let best=slot;if(activeStage(slot)){const pool=bank.filter(q=>eligible(q,slot,chosenFamilies,chosenIds,seen,recent,helpers));pool.sort((a,b)=>score(b,p,seen,recent,helpers)-score(a,p,seen,recent,helpers)||String(a.id).localeCompare(String(b.id)));best=pool[0]||slot}if(!best||chosenIds.has(best.id)||chosenFamilies.has(family(best,helpers)))return existing;chosen.push(best);chosenIds.add(best.id);chosenFamilies.add(family(best,helpers))}if(existing.filter(q=>q?.kind==='visual').length!==chosen.filter(q=>q?.kind==='visual').length)return existing;if(!sameProfile(originalStages,stageProfile(chosen)))return existing;for(const [subject,count] of Object.entries(expected))if(chosen.filter(q=>q.subject===subject).length!==count)return existing;return chosen}catch(_){return existing}}
function graph(bank=window.AW_BANK){const out=new Map();for(const q of Array.isArray(bank)?bank:[]){const id=skillId(q);if(!out.has(id))out.set(id,{id,grade:gradeOf(q),stage:stageOf(q),subject:q.subject,name:skillName(q),questionCount:0});out.get(id).questionCount++}return [...out.values()].sort((a,b)=>a.grade-b.grade||a.subject.localeCompare(b.subject)||a.name.localeCompare(b.name))}
function targetScores(bank,p){const out={};for(const subject of ['English','Mathematics','Science']){const qs=(Array.isArray(bank)?bank:[]).filter(q=>q.subject===subject&&stageOf(q)==='icas-y2');out[subject]=(TARGETS[subject]||[]).map(([id,label,mode,aliases])=>{const direct=qs.filter(q=>skillId(q)===id).length,inferred=qs.filter(q=>aliases.some(a=>searchText(q).includes(a))).length,count=Math.max(direct,inferred),stats=p?.skillStats||{};let a=0,c=0;for(const [k,v] of Object.entries(stats))if(k.startsWith(subject+'|')&&aliases.some(x=>k.toLowerCase().includes(x))){a+=Number(v?.a)||0;c+=Number(v?.c)||0}const acc=a?c/a:null;return{id,label,mode,count,priority:(count===0?1000:300/Math.max(1,count))+(acc==null?80:(1-acc)*100)}})}return out}
function normalRequired(unseen={}){const deficits=Object.fromEntries(['English','Mathematics','Science'].map(s=>[s,Math.max(0,30-Number(unseen[s]||0))]));return Object.values(deficits).some(Boolean)?deficits:{English:10,Mathematics:10,Science:10}}
function coveragePlan(baseRequestKey,bank=window.AW_BANK,p={},requiredBySubject={}){const base=String(baseRequestKey||'aw-topup').replace(/-sg[0-9a-z]+$/,'');const scores=targetScores(bank,p);let best=null;for(let nonce=0;nonce<64;nonce++){const key=`${base}-sg${nonce.toString(36)}`;let value=0;const focus={};for(const subject of ['English','Mathematics','Science']){const n=Math.min(6,Math.max(0,Number(requiredBySubject[subject]||0))),offset=fnv(`${key}|${subject}|recipe`)%12;focus[subject]=[];for(let i=0;i<n;i++){const mode=(offset+i)%12,t=scores[subject].find(x=>x.mode===mode);if(t){value+=t.priority;focus[subject].push(`${t.id}|${t.label}|mode:${t.mode}`)}}}if(!best||value>best.value)best={requestKey:key,value,focusSubskills:focus}}return best||{requestKey:base,value:0,focusSubskills:{English:[],Mathematics:[],Science:[]}}}
function coverageRequestKey(base,bank=window.AW_BANK,p={},unseen={}){return coveragePlan(base,bank,p,normalRequired(unseen)).requestKey}
window.__AW_SKILL_ENGINE={version:'y2-y4-v1',skillId,skillName,stageOf,gradeOf,graph,rebalance,coveragePlan,coverageRequestKey,generationTargets:TARGETS,activeStages:[...ACTIVE_STAGES]};
})();
