(()=>{
'use strict';
let pollTimer=0,polling=false;
const ACTIVE=new Set(['queued','generating','review','expert_review','approved']);
function collapseSubskills(){document.querySelectorAll('.aw-subject-panel').forEach(panel=>{if(panel.dataset.awCollapsible==='1')return;const spectrum=panel.querySelector('.aw-subskill-spectrum');if(!spectrum)return;panel.dataset.awCollapsible='1';const subject=panel.querySelector('.aw-subject-head small')?.textContent?.trim()||'Subject',attempted=panel.querySelector('.aw-subject-head>span')?.textContent?.trim()||'',details=document.createElement('details'),summary=document.createElement('summary');details.className='aw-subskill-details';details.dataset.parentSubskills=subject;summary.setAttribute('role','button');summary.setAttribute('aria-expanded','false');summary.innerHTML=`<span><b>Subskill performance</b><small>${attempted}</small></span><i aria-hidden="true">⌄</i>`;details.addEventListener('toggle',()=>summary.setAttribute('aria-expanded',String(details.open)));details.append(summary,spectrum);panel.append(details)})}
function schedulePoll(delay=5000){clearTimeout(pollTimer);if(document.querySelector('[data-aw-insights="1"]'))pollTimer=setTimeout(pollStatus,delay)}
async function pollStatus(){if(polling||!document.querySelector('[data-aw-insights="1"]'))return;const api=window.__AW_TOPUP_API,current=api?.load?.();if(!current||!ACTIVE.has(current.backendStatus)){if(current?.backendStatus==='released')window.__AW_RELEASED_BANK_API?.refresh?.();return}polling=true;try{const next=await api.refreshStatus();if(next?.backendStatus!==current.backendStatus)api.render?.();if(next?.backendStatus==='released')await window.__AW_RELEASED_BANK_API?.refresh?.();else if(ACTIVE.has(next?.backendStatus))schedulePoll()}finally{polling=false}}
function sync(){collapseSubskills();const status=window.__AW_TOPUP_API?.load?.()?.backendStatus;if(ACTIVE.has(status)&&!pollTimer)schedulePoll(800)}
let q=false;function schedule(){if(q)return;q=true;requestAnimationFrame(()=>{q=false;sync()})}
new MutationObserver(schedule).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});sync();
window.__AW_PARENT_UI={subskillsCollapsedByDefault:true,statusPolling:true};
})();